// Issue a one-time LINE binding code for a member (Phase 5B Slice 2). The operator hands the
// printed code to a KNOWN member out-of-band; the member sends `綁定 <code>` to the OA (5A capture),
// then the operator approves (binding:approve). A random code is generated by default.
//   npm run binding:issue -- --user-id <uuid> --ttl-days 14
//   npm run binding:issue -- --user-id <uuid> --ttl-days 14 --code ABCD-2345 --note "小組長轉交"
//
// ⚠️ The code is printed ONCE here (the operator must relay it). A code passed via --code may be
// retained in shell history / the process list — prefer the generated default.
try {
  process.loadEnvFile('.env.local')
} catch {
  /* env may be provided by the shell instead */
}

import { issueBindingCode } from '../server/services/bindingAdminService'

function argValue(flag: string): string | undefined {
  const i = process.argv.indexOf(flag)
  return i >= 0 ? process.argv[i + 1] : undefined
}

async function main() {
  const userId = argValue('--user-id')
  const ttlRaw = argValue('--ttl-days')
  if (!userId || !ttlRaw) {
    throw new Error('usage: binding:issue --user-id <uuid> --ttl-days <n> [--code ABCD-2345] [--created-by <text>] [--note <text>]')
  }
  const ttlDays = Number(ttlRaw)

  const issued = await issueBindingCode({
    userId,
    ttlDays,
    code: argValue('--code'),
    createdBy: argValue('--created-by') ?? null,
    note: argValue('--note') ?? null,
  })

  // The ONLY place a full code is printed — the operator relays it to the member.
  console.log(`Binding code for ${issued.displayName} (user ${issued.userId}):`)
  console.log(`  ${issued.code}`)
  console.log(`  expires: ${issued.expiresAt}`)
  console.log('Relay this code to the member; they send `綁定 <code>` to the OA, then run binding:approve.')
}

main().catch(err => {
  console.error(err instanceof Error ? err.message : err)
  process.exit(1)
})
